variables:
  DOCKER_TLS_CERTDIR: "/certs"
  BASE_DOMAIN: cct-ev.de


.install-ssh: &install-ssh
  - "which ssh-agent || ( apk update && apk add openssh-client )"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.docker-compose-run: &docker-compose-run
  - COMPOSE_PROJECT_NAME=portal-$CI_ENVIRONMENT_SLUG docker-compose -f docker-compose.yml pull
  - COMPOSE_PROJECT_NAME=portal-$CI_ENVIRONMENT_SLUG docker-compose -f docker-compose.yml up -d




stages:
  - lint
  - test
  - build
  - deploy

lint:
  image: node:lts
  stage: lint
  needs: []
  cache:
    paths:
      - node_modules
  script:
    - npm install --progress=false
    - VUE_APP_ENV=dev npm run lint


test:
  image: node:lts
  stage: test
  needs: []
  cache:
    paths:
      - node_modules
  script:
    - npm install --progress=false
    - VUE_APP_ENV=dev npm run test:unit


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  variables:
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" 
  script:
    - docker pull $IMAGE || true
    - docker build --cache-from $IMAGE -t $IMAGE .
    - docker push $IMAGE



deploy stag: 
  extends: 
    - .deploy base
  environment:
    name: stag
    url: https://portal.stag.$BASE_DOMAIN
    on_stop: stop stag
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.stag.${BASE_DOMAIN}'
    DOMAIN: "portal.stag.${BASE_DOMAIN}"
  only: 
    - master

stop stag:
  only:
    - master
  extends: 
    - .stop base
  environment:
    name: stag
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.stag.${BASE_DOMAIN}'
    DOMAIN: "portal.stag.${BASE_DOMAIN}"

deploy review: 
  extends: 
    - .deploy base
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.portal.stag.$BASE_DOMAIN
    on_stop: stop review
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.stag.${BASE_DOMAIN}'
    DOMAIN: "$CI_ENVIRONMENT_SLUG.portal.stag.${BASE_DOMAIN}"
  only: 
    - branches
  except:
    - production
    - master
    - tags


stop review:
  only:
    - branches
  except:
    - production
    - master
    - tags
  extends: 
    - .stop base
  environment:
    name: review/$CI_COMMIT_REF_NAME
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.stag.${BASE_DOMAIN}'
    DOMAIN: "$CI_ENVIRONMENT_SLUG.portal.stag.${BASE_DOMAIN}"

deploy production:
  image: docker:latest
  stage: deploy
  needs: 
    - job: build
      artifacts: false
  only: 
    - tags
  environment:
    name: prod
    url: https://portal.$BASE_DOMAIN
    on_stop: stop production
  extends: 
    - .deploy base
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.${BASE_DOMAIN}'
    DOMAIN: "portal.${BASE_DOMAIN}"
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"


stop production:
  only:
    - tags
  extends: 
    - .stop base
  environment:
    name: prod
  variables:
    DOCKER_HOST: 'ssh://gitlab-ci@portal.${BASE_DOMAIN}'
    DOMAIN: "portal.${BASE_DOMAIN}"



# templates

.deploy base:
  image: docker:latest
  stage: deploy
  needs: 
    - job: build
      artifacts: false
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$BASE_DOMAIN
    on_stop: stop review
  variables:
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  before_script:
    - *install-ssh
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - *docker-compose-run

.stop base:
  image: docker:latest
  stage: deploy
  needs: 
    - job: build
      artifacts: false
  environment:
    action: stop
  when: manual
  variables:
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  before_script:
    - *install-ssh
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - COMPOSE_PROJECT_NAME=portal-$CI_ENVIRONMENT_SLUG docker-compose -f docker-compose.yml down -v

