version: "3.3"
services:
  frontend:
    image: $IMAGE
    restart: unless-stopped
    networks: 
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}-frontend.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${STACK_NAME}-frontend.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACK_NAME}-frontend.loadbalancer.server.port=80"

networks: 
  traefik:
    external: true
